all:
	gcc fork_server.c -o fork_server
    gcc thread_server.c -o thread_server
    gcc select_server.c -o select_server
    gcc poll_server.c -o poll_server
    gcc epoll_server.c -o epoll_server

clean:
    rm fork_server thread_server select_server poll_server epoll_server
    